hidden_dim: 1024
esm_dim: 640
warmup_epochs: 2
base_lr: 1e-3

dataset: TALE
datasets_path: './data_tale/'
mode: test                    # [train/test]
namespace: CC                 # [BP/CC/MF]

# hier_reg_lambda: 0.1          # 层级损失的基础权重
# hier_lambda_warmup: 10        # λ 线性增长的 epoch 数
# hier_lambda_max: 0.5          # λ 增长的上限

